### ISSUE TITLE
Issues getting up and running.

### ISSUE THREAD

**Issue by LuisFX** [gianfrancodemarco/converso-chatbot#1]
Trying to get the solution up and running.

## Installed Deps:
helm - v3.15.3
skaffold - v2.12.0
kubectl - v1.29.4
minikube - v1.33.1
python - v3.12.3 (venv)

## Questions
1. There is secrets-example.yaml for several services, but not in the /{project_root}/.skaffold directory. Can we provide an example for this file?

2. There's also a client_secret.json file expected in the root directory. Can we provide and example of this file?

## Errors
Upon trying to stand up the services with:

```
skaffold run
```

I get the following error:

```
- converso-telegram-bot: Error checking cache.
getting hash for artifact "converso-telegram-bot": getting dependencies for "converso-telegram-bot": unable to evaluate build args: reading dockerfile: open /<full_path>/converso-chatbot/.docker/converso_telegram_bot.Dockerfile: no such file or directory
```

**Comment by LuisFX** [comment]
The last error was just a misspelling of the telegram Dockerfile.

**Comment by gianfrancodemarco** [comment]
Hi @LuisFX,

1) This is just actually a configuration file, it doesn't need to be ignored; I've added it to the PR
2) I've added a section to the readme for instructions on how to generate this

Would you mind sharing if you can get this up & running so I merge the PR?

**Comment by LuisFX** [comment]
Hi @gianfrancodemarco, I just got back from a trip. I'll give this PR a run right away and let you know.

**Comment by LuisFX** [comment]
Hi there again, I think the services are now running fine. I took the liberty to update the readme which outlines every step I had to follow (including installing all the dependencies).

[README.md](https://gist.github.com/LuisFX/43742c67b60d571ae39e2f7d2efce055)

This is the final output after running: `skaffold run`

![image](https://github.com/user-attachments/assets/4fc6736a-9d50-4503-b39e-7affc748cae3)

Full disclaimer, I had never heard of skaffold, so I'm going to read up on it a bit, because I don't know where to go from here to actually test the app/bot. 

Also, I'm not sure if the telegram API token creation that I followed in the link (the one I added to the updated readme) are the correct instructions for this demo, so please let me know.

If you can give me some pointers/instructions on what to do once the `skaffold run` command runs successfully, I'd appreciate it. I'll update the readme once it's all running as expected.

**Comment by LuisFX** [comment]
Ok, after reading "a little bit more", it seems that I needed to run `skaffold dev`

After that, I started to get this output in my terminal:

![image](https://github.com/user-attachments/assets/d7431435-5494-4f36-b4c5-1dc90f933612)

With the last line printing every 10 secs:
`[converso-telegram-bot] 2024-07-31 18:08:43,765 INFO HTTP Request: POST https://api.telegram.org/bot7022587365:AAH4TP5x_cmjwjFokpa15c-Uz3mvGKK_UKM/getUpdates "HTTP/1.1 200 OK"`
(Which I assume indicates the services is running and listening.)

After that, I started a chat with the newly created bot in Telegram, and just said "hi", but I get no response, and the terminal displays:

![image](https://github.com/user-attachments/assets/5e0484d1-753a-4735-80e7-7d473f309022)

**Comment by gianfrancodemarco** [comment]
I'm out of town for a few days but I'll try to help get it up and running.
Yes, `skaffold dev` is the correct command to run in development mode.

Your bot is getting the message from Telegram and trying to retrieve the conversation history from redis, but it cannot authenticate.

The fix should be to set `password` as REDIS_PASSWORD in .`kubernetes%2Fconverso%2Fsecrets.yaml`.

You should then probably stop skaffold and rerun the dev command.

> Ok, after reading "a little bit more", it seems that I needed to run `skaffold dev`
> 
> After that, I started to get this output in my terminal:
> 
> ![image](https://github.com/user-attachments/assets/d7431435-5494-4f36-b4c5-1dc90f933612)
> 
> With the last line printing every 10 secs:
> `[converso-telegram-bot] 2024-07-31 18:08:43,765 INFO HTTP Request: POST https://api.telegram.org/bot7022587365:AAH4TP5x_cmjwjFokpa15c-Uz3mvGKK_UKM/getUpdates "HTTP/1.1 200 OK"`
> (Which I assume indicates the services is running and listening.)
> 
> After that, I started a chat with the newly created bot in Telegram, and just said "hi", but I get no response, and the terminal displays:
> 
> ![image](https://github.com/user-attachments/assets/5e0484d1-753a-4735-80e7-7d473f309022)
>

**Comment by LuisFX** [comment]
Understood regarding your travels!! I appreciate that you're even replying...

In case you get another free sec here and there, and you're bored:

You were right about the redis password, I had a typo, so thanks for that! ...

Now that we got past that error, I'm trying to submit some commands from the Telegram chat (/reset, and /login_to_google).

The `/reset` command **DOES** return a message to Telegram app: "Conversation history cleared" (so we know the conversation **IS** engaging with the api, but the terminal shows an error deleting the messages:

![image](https://github.com/user-attachments/assets/8290593b-de0d-49b6-a982-d1166a47e37f)

...also`/login_to_google` returns an error, but I'm assuming the error is related to the fact that I commented out the line in the Dockerfile as per your notes...

![image](https://github.com/user-attachments/assets/e5aca12a-9076-4fc1-bf64-003e222347f1)

If I send an arbitrary message such as 'test', I get this error:

![image](https://github.com/user-attachments/assets/ffaf02f0-6ce6-41d3-b83a-440db8dba11c)


It seems to still point to a redis error, but I'm sure I triple-checked the passwords match:

![image](https://github.com/user-attachments/assets/33508cb8-06de-43a1-82bc-7ac0044f0fed)

Anyway, thanks again for your help. Safe travels!

**Comment by gianfrancodemarco** [comment]
This should be easy!

On the coverso secret, you should put the password in plain (_password_), as it uses stringData instead of data.

Probably this inconsistency is confusing, and mostly due to laziness.

**Comment by LuisFX** [comment]
![image](https://github.com/user-attachments/assets/a1a20af2-f834-468f-85f6-eb717bf2bac1)

It's working!! This is great... much obliged!!

I have a bunch of ideas on how this provides utility, enjoy your trip and I'll try to understand things under the hood in the mean time.

Thanks again!

**Comment by LuisFX** [comment]
By the way, I updated the readme for what worked for me (in case it might help others)

[updated readme](https://gist.github.com/LuisFX/43742c67b60d571ae39e2f7d2efce055)

Cheers!

**Comment by gianfrancodemarco** [comment]
Hi @LuisFX! 
If you want, open a PR with the README and i'll merge that in!
